### ISSUE TITLE
Kauri implementation does not function

### ISSUE THREAD

**Issue by funkemunky** [JustinDevB/VulcanReplay#5]
The registering of the kauri listeners will not function as they use the Atlas event system, and therefore will not run. My original pull request implemented this change properly.

**Comment by JustinDevB** [comment]
I’ll fix that after the holidays.

**Comment by JustinDevB** [comment]
I believe I have fixed this here: https://github.com/JustinDevB/VulcanReplay/tree/Kauri-Implementation

Please verify that this will work since I do not have Kauri to test it on.
